### ISSUE TITLE
Сбрасывается настройка языка интерфейса в админке

### ISSUE THREAD

**Issue by padlyuck** [Indomian/KS-CMS#10]
Баг возник при попытке поменять настройки сайта.
Изначально в конфиге был прописан русский язык, записи pkey и update_server были оставлены мною пустыми. при попытке изменить стартовую страницу админки через интерфейс цмс я получил следующие сообщения об ошибке:
1.Ошибка: Возникли ошибки при заполнении формы настроек. 
2.Вы не ввели ключ продукта и не сможете получать обновления. Для того, чтобы получать обновления необходимо ввести правильный ключ продкта и правильный адрес сервера обновлений.
3.Неверный адрес сервера обновлений. 
После заполнения полей "Ключ продукта" и "Адрес сервера обновлений" жму сохранить и получаю интерфейс на английском языке. повторная установка языка на русский вернула все на свои места.

**Comment by lopikun** [comment]
Ключ -demo
Адрес сервера обновлений - любой
Мне ето помогло

**Comment by Indomian** [comment]
Думаю добавлю значение языка по умолчанию, это будет верно. А то малоли кто не введет.

**Comment by Indomian** [comment]
Установил язык по умолчанию на ru
