### ISSUE TITLE
Модуль карта

### ISSUE THREAD

**Issue by padlyuck** [Indomian/KS-CMS#13]
1.При нажатии на кнопку установить модуль происходит переход на страницу админки с надписью

> KOLOS-CMS    Управление модулями    Установка модуля
> Установка модуля
> Установка модуля sitemap

Оповещения о том что модуль установлен система не выдает.
2.Следующий баг возникает при попытке зайти в настройки модуля:
заходим в настройки модуля, ничего не меняя и не сохраняя нажимаем на ссылку "Карта сайта" в цепочке навигации и получаем следующее сообщение об ошибке:

> Ошибка: Модуль не имеет пользовательской части 110
> Ошибка: Страница не найдена

**Comment by Indomian** [comment]
Хм не могу подтвердить ни одной из указанных ошибок. Модуль успешно устанавливается и удаляется стандартными кнопками. Необходимо уточнение.

**Comment by Indomian** [comment]
Проверил ещё раз на последней сборке., первую ошибку не подтверждаю. Вторая ошибка подтверждена, добавил переход на настройки модуля.
