### ISSUE TITLE
Ошибка в редакторе шаблонов (генератор кода виджета)

### ISSUE THREAD

**Issue by lopikun** [Indomian/KS-CMS#15]
При попытке открыть генератор кода выбивает ошибку  
Fatal error: Cannot instantiate abstract class CModuleManagment in /modules/main/pages/widget.php on line 119

**Comment by Indomian** [comment]
Это когда? В новой версии или какойто определённый виджет? У меня всё в порядке.

**Comment by Indomian** [comment]
Аааа - это редактор шаблонов???? Блин я не понял сразу. Он пока не обновлялся, скорее всего я его уберу.

**Comment by Indomian** [comment]
Редактор шаблонов удалён.
