### ISSUE TITLE
На страницу выводятся тексты запросов к БД

### ISSUE THREAD

**Issue by padlyuck** [Indomian/KS-CMS#20]
Похоже на то что гдето не закоментирована эха и запросы к БД выводятся на страницу

**Comment by padlyuck** [comment]
Продебажил, оказалось что запросы выводятся из-за того что не задана константа KS_DEBUG_QUERIES в db_config.php, поэтому в class.CMain.php срабатывает условие на строке 1143

**Comment by padlyuck** [comment]
На всякий случай задал константы KS_DEBUG_QUERIES и KS_DEBUG . Вроде работает.

**Comment by Indomian** [comment]
Т.е. получалось, что если нет константы, сообщения выводились?

**Comment by padlyuck** [comment]
да. не знаю с чем это связано. по идее такого не должно было быть.

**Comment by Indomian** [comment]
Проверил, действительно если константа не установлена он всё печатает. Будет исправлено в ближайшем патче.
