### ISSUE TITLE
Не обрабатывается exception

### ISSUE THREAD

**Issue by padlyuck** [Indomian/KS-CMS#22]
Баг замечен в админке. Если в конфиге указать неправильные доступы к БД админка падает с ошибкой
Fatal error: Call to a member function IsLogin() on a non-object in /var/www/admin.php on line 356

**Comment by Indomian** [comment]
Это фатальная ошибка, надо будет предусмотреть проверку доступа к БД и если она не прошла, гарантированно падать без проверки прав, принято в разработку

**Comment by Indomian** [comment]
Проверяю в текущей версии

**Comment by Indomian** [comment]
Ошибка не повторяется, считаю что она исправлена.
