### ISSUE TITLE
Не работает привязка

### ISSUE THREAD

**Issue by padlyuck** [Indomian/KS-CMS#23]
Катсубкат падает при вызове его в привязках. решение: добавить глобальную переменную в файле /modules/catsubcat/pages/index.php на 481 строке.
    function Run()
    {
        global $KS_URL, $smarty;
        //Проверка прав доступа

**Comment by Indomian** [comment]
Которую из? $smarty там по идее не нужен, можно делать $this->smarty. А вот $KS_URL нужен.

**Comment by Indomian** [comment]
Переношу в 2.6.1
