### ISSUE TITLE
Баг с загрузкой файлов

### ISSUE THREAD

**Issue by padlyuck** [Indomian/KS-CMS#24]
в /modules/main/libs/class.CFilesObject.php на 169 строке добавить префикс. в противном случае теряется файл который загружаем.
$obUploadManager=new CFileUploader($prefix . $key,$this->sTable);

**Comment by Indomian** [comment]
В последнем патче баг не наблюдается, на 169-ой строке другой код, на строке ниже https://github.com/Indomian/KS-CMS/commit/e3f784326bb7be87a10df5240baf15135c505012#L4R173 внесены соответствующие исправления.
