### ISSUE TITLE
Баг с корзиной модуля катсубкат(удаление по элементно)

### ISSUE THREAD

**Issue by padlyuck** [Indomian/KS-CMS#25]
1. Удаляем в корзину категорию
2. Переходим в корзину
3. Жмем "Удалить" напротив категории
4. Получаем сообщение о невозможности удаления корневого элемента, хотя пытались удалить не корневой элемент.
   У себя решил путем добавления в шаблоне catsubcat_basket.tpl на 77 строке проверки на тип элемента и замену в урле параметра CSC_id на CSC_catid в зависимости от типа элемента

**Comment by Indomian** [comment]
Надо проверять, вполне возможно, что баг присутствует, поставил в очередь на исправление

**Comment by Indomian** [comment]
Переношу в 2.6.1
