### ISSUE TITLE
Баг с корзиной модуля катсубкат(восстановление поэлементно)

### ISSUE THREAD

**Issue by padlyuck** [Indomian/KS-CMS#26]
1. Удаляем категорию содержащую вложенные страницы
2. Переходим в корзину
3. Жмем кнопку восстановить напротив только что удаленной категории
4. Читаем предупреждение о том что будут восстановлены вложенные элемента, соглашаемся.
5. После перезагрузки видим что категория восстановилась, а вложенные элементы попрежнему лежат в корзине.

**Comment by Indomian** [comment]
Да, баг возможен, поставлен в очередь на исправление

**Comment by Indomian** [comment]
Корзина временно отключена, будет предложена новая архитектура, переношу в 2.6.1
