### ISSUE TITLE
Перенос файлов из каталога /cnf в каталог /modules/main

### ISSUE THREAD

**Issue by Indomian** [Indomian/KS-CMS#28]
Предлагаю выполнить перенос файлов из каталога /cnf в каталог /modules/main каждый файл в соответствующее место. Например sys_config в /modules/main/config.php; db_config в /modules/main/libs/db/db_config.php и т.д. Что вы думаете по этому поводу?

**Comment by padlyuck** [comment]
Мне кажется это имеет смысл сделать, если отпадет необходимость править конфиги руками при установке. Будет шикарно избавиться от лишней директории, но необходимость лазить по директориям во время установки не радует

**Comment by lopikun** [comment]
Мне кажется не удобно. Почему:
1. частенько в самом начале есть нужда туда заскакивать, т.е. я заменяю sys_config и db_config (причем одновременно)
2. права на запись, можно случайно еще что-то прихватить.
3. папка cfg говорит сама за себя, что ее правим в 1ю очередь.

**Comment by lopikun** [comment]
ну если не надо будет их править, и права у них уже будут стоять те что нужны, то ето большой +

**Comment by Indomian** [comment]
Идея вообще вот в чём, если перенести эти файлы, то можно будет разместить каталог modules выше ROOT_DIR веб сервера, тем самым повысив безопасность. Т.е. в корне сайта будет лежать только index.php, admin.php и каталог /uploads/
Тем более конфиги лучше хранить отдельно. Кстати сейчас конфиг sys_config.php обычно системой правиться не так как все остальные конфиги, что создаёт неудобства при программировании.

**Comment by lopikun** [comment]
В плане безопасности согласен, главное без прямого рукоприкладства  при развертывании

**Comment by Indomian** [comment]
А если я приделаю в инсталлятор интерфейс для настройки полей в БД? Плюс по идее их не так часто надо менять. Файлы version, db_structure, events_config, smarty вообще менять не надо. Только при разработке.

**Comment by Indomian** [comment]
Вообщем думаю это тогда можно поставить в очередь на разработку и выполнить когда будет время. Согласны?

**Comment by sirkonst** [comment]
В плане переноса выше ROOT_DIR идея правильная как таковая, но в ряде случаев не возможна, т.к. не на всех хостингах так можно сделать - и это ставит крест на идее.

**Comment by Indomian** [comment]
Ну по меньшей мере проще закрыть 1 заведомо опасный каталог чем пачку, даже в htaccess это будет легче сделать я думаю.

**Comment by sirkonst** [comment]
Можно подготовить htaccess с нужными правилами. Но "перенос выше" лучше не делать из-за "совместимости".

**Comment by Indomian** [comment]
Ну его можно оставить как опциональный я думаю. Но перенос конфигов по местам их размещения не завязан на обязательный перенос.

**Comment by lopikun** [comment]
Я за вариант выбора.

**Comment by padlyuck** [comment]
А я теперь с миру по нитке соберу и выскажу конечное пожелание:
Опциональный перенос modules выше DocumentRoot
Интерактивный инсталятор без необходимости править конфиги руками
Если будет и то и то - будет круто!

**Comment by Indomian** [comment]
Так что с конфигами то делаем? Переносим?

**Comment by padlyuck** [comment]
я ЗА но тогда нужно реализовывать интерактивный инсталятор

З.Ы. Я че с перепугу прошлым своим коментом закрыл обсуждение? xD

**Comment by Indomian** [comment]
Ок тогда делаю две задачи: перенос и добавление настроек базы данны в инсталятор системы. На том и порешили
