### ISSUE TITLE
Права на файлы.

### ISSUE THREAD

**Issue by Demosfen** [Indomian/KS-CMS#41]
Добавить в wiki пункт по правам доступа:
# chmod 0777 -R /<path>

**Comment by padlyuck** [comment]
а смысл так радикально?

**Comment by Demosfen** [comment]
У тебя в wiki первым пунктом стоит удалить /templates/ . Цитирую:"Спокуха, ничего удалять не надо..."

**Comment by Demosfen** [comment]
Да там стоял "/<path>", но его вырезал редактор.

**Comment by Demosfen** [comment]
Блин, в смысле "/(path)" в угловых скобках, как у тэга. Я не учёл, что тут нет форматирования и HTML вырезается

**Comment by padlyuck** [comment]
я догадался что после слеша должен стоять путь, все равно непонятно зачем делать права 777. по большому счету система будет работать с правами 700. а templates можно и ручками удалить.
Сложности возможны только в том случае если пользователь фтп и пользователь под которым запущен вебсервер не совпадают.

**Comment by Indomian** [comment]
Короче мысль о том, что надо написать про подготовительные действия, т.е. вообще права проверить и базу. Кстати надо сделать ещё адекватные тексты ошибок при установке.

**Comment by Indomian** [comment]
Добавил упоминание о правах в руководство

**Comment by sirkonst** [comment]
chmod 0777 -R / - сделает все файлы ВЫПОЛНЯЕМЫМИ, правильнее так: chmod =rwX -R path/
