### ISSUE TITLE
Добавить chmod

### ISSUE THREAD

**Issue by MimaTomis** [Indomian/KS-CMS#42]
Добавить возможность изменения прав доступа ко всем файлам и директориям. Это дело облегчит участь юзера, пользующего систему.

**Comment by Indomian** [comment]
А как лучше это сделать? По идее только через файловый менеджер, или при установке? Пока не особо понятна цель, а главное средства.

**Comment by Indomian** [comment]
Вообщем решили ничего не делать пока, тикет закрываю до лучших времён.
