### ISSUE TITLE
php mistake???

### ISSUE THREAD

**Issue by Demosfen** [Indomian/KS-CMS#43]
Не уверен, но вроде бы у тебя в файле db_config.php.src отсутствует закрывающая конструкция в конце файла: ?>

Или так должно быть?

**Comment by padlyuck** [comment]
по нотации зенда закрывающий пхп тэг не просто необязателен, но и не желателен. если отсутствие закрывающего тега не вызывает ворнингов и нотисов - значит все нормально:)

**Comment by Indomian** [comment]
Так и должно быть, это допускается если файл не должен выводить ничего
в поток вывода.

25.06.11, Demosfenreply@reply.github.com
написал(а):
