### ISSUE TITLE
Прикрепление файлов

### ISSUE THREAD

**Issue by padlyuck** [Indomian/KS-CMS#49]
В административной части в частности в модуле текстовых страниц есть возможность прикрепить к материалу фото путем аплоада этого файла на сервер. Очень необходимо бывает вместо аплоада выбрать файл который уже присутствует в файловой системе сайта. Эта же фича очень была бы кстати и в доп. полях типа файл.

**Comment by Indomian** [comment]
В подготовку 2.6.1, на 2.6 наверное не будем обкатывать, т.к. в 2.6 нет окон в слое, в 2.6.1 они вернутся.
