### ISSUE TITLE
Отсутствует поле "Активность" для пунктов меню

### ISSUE THREAD

**Issue by padlyuck** [Indomian/KS-CMS#8]
В данный момент можно полностью отключить меню, но нет возможности сделать неактивными отдельные пункты меню.

**Comment by Indomian** [comment]
Да это действительно важный функционал, если кто возьмётся реализовать добавлю в основную ветку

**Comment by lopikun** [comment]
Реализовал в ветке fox https://github.com/lopikun/KS-CMS/commit/fe7cce99b1576735b2c5b25994254305c67c075b

**Comment by Indomian** [comment]
Добавил код из ветки Фокса. Добавил еще редактирование активности при редактировании пункта меню.
